# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumposts',
            name='content_text',
            field=models.CharField(default='text', max_length=500),
            preserve_default=False,
        ),
    ]
