# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forumposts_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumposts',
            name='idSubcategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumposts',
            name='idUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumposts',
            name='isPoll_bool',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='forumposts',
            name='parentPost',
            field=models.IntegerField(default=0),
        ),
    ]
