# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20161128_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumPollsOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPost', models.IntegerField(default=0)),
                ('forumPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forumPosts')),
            ],
        ),
    ]
