# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_forumpollsoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='forumposts',
            name='idUser',
        ),
    ]
