# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20161128_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumposts',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forums.users'),
            preserve_default=False,
        ),
    ]
