# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_forumposts_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumposts',
            name='idUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forums.users'),
        ),
    ]
