# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_forumposts_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.IntegerField(default=1),
        ),
    ]
