# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_auto_20161128_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumposts',
            name='idUser',
        ),
    ]
