# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_remove_forumposts_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumposts',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forums.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
