# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_auto_20161128_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('date_stamp', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.users')),
            ],
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='parentPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.thread'),
        ),
    ]
