# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_auto_20161129_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('userpassword', models.CharField(max_length=128)),
                ('useremail', models.CharField(max_length=128)),
                ('userdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.user'),
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='thread',
            name='forumuser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forums.user'),
            preserve_default=False,
        ),
    ]
