# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_auto_20161219_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userDob',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 16, 17, 35, 650618, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
