# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_user_userdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDob',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userdate',
            field=models.DateTimeField(verbose_name='date registered'),
        ),
    ]
