# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0017_auto_20161227_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
            ],
        ),
    ]
