# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_forumcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpollsoptions',
            name='forumPost',
        ),
        migrations.DeleteModel(
            name='forumPollsOptions',
        ),
    ]
