# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_auto_20170102_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('content_text', models.CharField(max_length=500)),
                ('date_stamp', models.DateTimeField(verbose_name='date published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forumCategory')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='forumposts',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='forumposts',
            name='parentPost',
        ),
        migrations.DeleteModel(
            name='forumPosts',
        ),
    ]
