# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0021_auto_20170102_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='forumuser',
            new_name='idUser',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
        migrations.AddField(
            model_name='thread',
            name='idForumPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forums.forumPost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='date_stamp',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
    ]
