# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0022_auto_20170103_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content_text',
            field=models.CharField(default='NoTextAvailable', max_length=500),
            preserve_default=False,
        ),
    ]
