# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_thread_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 18, 33, 14, 359571, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
