# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_auto_20170115_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userdate',
            field=models.DateTimeField(verbose_name='date registered'),
        ),
    ]
