# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0027_auto_20170116_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='idForumSubcategory',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='ifForumCategory',
        ),
    ]
