# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0028_auto_20170116_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.CharField(max_length=128, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpassword',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
