# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 13:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0030_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/site_media/user_data/images/'), upload_to=b'/site_media/user_data/images/'),
        ),
    ]
