# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0032_auto_20170130_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDob',
            field=models.DateTimeField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userdate',
            field=models.DateTimeField(null=True, verbose_name='date registered'),
        ),
    ]
