# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0033_auto_20170130_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
