# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0034_thread_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=90, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpassword',
            field=models.CharField(max_length=90, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='forum_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
