# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0035_auto_20170130_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_user',
            name='user_dob',
            field=models.DateTimeField(null=True, verbose_name='date of birth'),
        ),
    ]
