# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0037_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
