# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0038_forumpost_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
