# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0039_user_avatar_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
