# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-19 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0041_auto_20170219_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_et.jpg', null=True, upload_to='images'),
        ),
    ]
